FROM alpine:3.5
MAINTAINER sparklyballs-develop

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"

# install packages
RUN \
 apk add --no-cache \
	ca-certificates \
	curl
