#!/bin/bash

VERSION_TAG=${IMAGE_NAME#*:}
SONARR_BRANCH=${VERSION_TAG%-*}

DOCKER_BUILD_ARGS+=( --build-arg VERSION=$VERSION_TAG --build-arg SONARR_BRANCH=${SONARR_BRANCH})

if [[ $SONARR_BRANCH  == *[0-9]* ]]; then
SONARR_BUILD=${SONARR_BRANCH#*-}
DOCKER_BUILD_ARGS+=( --build-arg SONARR_BUILD=${SONARR_BUILD} )
fi

docker build \
${DOCKER_BUILD_ARGS[*]} \
--build-arg BUILD_DATE=`date -u +%B-%d-%Y-%H:%M:%S-UTC` -t $IMAGE_NAME .
