#!/bin/bash

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

# Tag and push image
    docker tag $IMAGE_NAME ${repoName}:develop
    docker push ${repoName}:develop

